### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by d3rt** [WebDevStudios/CMB2-User-Select#1]
Hey,

I guess the readme file have some issues. I think it should looks like this:

```
$cmb_term->add_field( array(
        'name'  => 'Author',
        'id'    => 'author',
        'desc'  => 'Type the name of the author and select from the options',
        'type'  => 'user_select_text',
        'options' => array(
            'minimum_user_level' => 0, // Enable search for all user levels.. use with caution.
        ),
 ) );
```

**Comment by jtsternberg** [comment]
The `$cmb2` variable (or `$cmb_term` in your case) is simply the variable you use when you create your metabox. [In this example](https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage#create-a-metabox) the variable is `$cmb`. In the [CMB2 example-functions.php](https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php) file, the variable is named differently with each box.
