### ISSUE TITLE
Remove hardcoded table prefix for _user_level meta key.

### ISSUE THREAD

**Issue by sandrodz** [WebDevStudios/CMB2-User-Select#4]
I can see new input, but search/autocomplete list never comes up.

<img width="807" alt="screen shot 2017-06-06 at 6 04 53 pm" src="https://cloud.githubusercontent.com/assets/8479569/26833140/abc47126-4ae2-11e7-8589-e3d12daeb57f.png">

**Comment by tw2113** [comment]
Check your browser console for possible js errors that may be causing conflicts. Also PHP errors could be playing a part in preventing returned results from AJAX

**Comment by sandrodz** [comment]
@tw2113 there are no errors in console. Returned data is simply empty:

<img width="1280" alt="screen shot 2017-06-06 at 6 24 21 pm" src="https://cloud.githubusercontent.com/assets/8479569/26834110/73481570-4ae5-11e7-89eb-afdd9656704b.png">

**Comment by sandrodz** [comment]
@tw2113 debugged it, problem is that meta_query key _user_level doesn't use table prefix, its hardcoded.

<img width="557" alt="screen shot 2017-06-06 at 6 48 43 pm" src="https://cloud.githubusercontent.com/assets/8479569/26835229/dfeb1756-4ae8-11e7-9306-179fe11b0941.png">

**Comment by tw2113** [comment]
I'm looking at a pretty stock WP install for my local dev and `wp_user_level` is what WordPress core uses for the meta key for user levels. That's not a custom key that CMB2 set, for example.

However, if you had changed that in the past somehow, then that would be a contributing factor.

**Comment by sandrodz** [comment]
@tw2113 WordPress changes key name based on table prefix. So key should use prefix.
<img width="606" alt="screen shot 2017-06-06 at 6 54 40 pm" src="https://cloud.githubusercontent.com/assets/8479569/26835606/b7918b54-4ae9-11e7-887c-fff76cf94136.png">

**Comment by tw2113** [comment]
ahhh. Good point.

With that said, so that you're not editing the plugin directly, you could use the filter right below it to safely modify the key to fetch.

`$user_args = apply_filters( 'wds_cmb2_user_select_search_args', $user_args, $this );
`

**Comment by sandrodz** [comment]
I think simpler/cleaner solution would be to make plugin compatible with WordPress option of changing table name prefix. Security conscience users will bump into this. Using filter is not an option, I randomly generate table prefixes on new install.

**Comment by sandrodz** [comment]
This could be a simple fix:
<img width="533" alt="screen shot 2017-06-06 at 7 10 42 pm" src="https://user-images.githubusercontent.com/8479569/26836430-e2ad434e-4aeb-11e7-8fb3-b8e492a97095.png">

**Comment by sandrodz** [comment]
@tw2113  I can do PR if you'd like.

**Comment by tw2113** [comment]
Just saying that it's technically possible to do it via the filter already provided. That said, PR it up, and we'll take it in.

**Comment by jtsternberg** [comment]
The user level thing needs to go away entirely. #3 is on the right path.

**Comment by sandrodz** [comment]
yep #3 looks great. Why was not it merged?

**Comment by tw2113** [comment]
because it slipped through the cracks and no one had taken care of it yet.

**Comment by sandrodz** [comment]
Is there an ETA for that PR? I looked through the code, nothing particularly problematic jumps out. But I could be wrong.

**Comment by tw2113** [comment]
Whenever someone gets around to it, to be honest. I'd appreciate some testing just in case, for what it's worth.

**Comment by tw2113** [comment]
Merged

**Comment by sandrodz** [comment]
Readme needs to be updated as well.

**Comment by sandrodz** [comment]
Can you please also release a new version?

**Comment by tw2113** [comment]
Good catch on the readme, that has been updated. Bumped/tagged.
