### ISSUE TITLE
What is saved and how to access it

### ISSUE THREAD

**Issue by richerimage** [WebDevStudios/CMB2-User-Select#6]
Hi

I'm noticing nothing is saved in custom fields?

I'm assuming we're saving the user ID?

If so, how can I access the ID for front-end use sine the custom field appear to be empty.

Thanks

**Comment by tw2113** [comment]
I believe it's going to save as post meta using a meta key matching the the 'id' value passed in. Much like other field types. I would assume either a user ID or a user login would be saved, and that could be fetched via get_post_meta() and then acted on afterwards.

**Comment by jazzsequence** [comment]
Both the user ID and the user login are saved. The field can optionally be set up to limit the user list to only those of a particular user role. See https://github.com/WebDevStudios/CMB2-User-Select/blob/master/lib/init.php#L47

**Comment by jazzsequence** [comment]
Looking at the sanitization callback, it looks like only the username(s) of the selected user(s) is stored: https://github.com/WebDevStudios/CMB2-User-Select/blob/master/lib/init.php#L162-L207

**Comment by richerimage** [comment]
Amazing how clearer things are after sleep!!

It does indeed get saved in a custom field as @tw2113 suggests (but it does not show in the post admin screen's Custom Fields metabox for some reason)

@jazzsequence the users ['name'] and ['id'] are the values stored (as a serialised array)

Thanks for your help guys!

**Comment by tw2113** [comment]
Glad we could help clarify. Let us know if you need anything else.
